// 深度-叙事引擎 · 存储目录映射表
// 所有模块统一通过此表获取中文存储目录名，不硬编码

var 存储目录 = {
  // 模块 key -> 中文目录名
  novel:         '情欲文学/成人小说',
  vignette:      '情欲文学/情色短章',
  fragment:      '碎片叙事',
  seriesWriting: '情欲文学/系列写作',
  comedy:        '情色杂物/闲情小品/段子',
  poetry:        '淫诗',
  qingShi:       '情诗',
  yinCi:         '艳词',
  yinQu:         '艳曲',
  guTiShi:       '古体艳诗',
  modernPoetry:  '现代艳诗',
  jindaiPoetry:  '近代艳诗',
  dirtyPoetry:   '打油艳诗',
  shanGe:        '民歌山歌',
  mengXueSanZiJing: '三字经艳典',
  mengXueDiZiGui:   '弟子规艳典',
  mengXueLunYu:     '论语艳典',
  eroticaAd:     '情色杂物/宣传发布/广告',
  flyer:         '情色杂物/宣传发布/传单',
  poster:        '情色杂物/宣传发布/海报',
  invitation:    '情色杂物/宣传发布/邀请函',
  eroticaDialogue:'淫语对白',
  eroticaFantasy:'性幻想设定',
  rp:            '互动RP',
  training:      '调教模拟',
  scriptKill:    '剧本杀',
  script:        '性爱台本',
  xiQuChangDuan: '戏曲唱段',
  tiaoJiaoDuiBai: '调教对白',
  aiMeiDuiBai:    '暧昧对白',
  zhiBoDuiBai:   '直播对白',
  xiangSheng:    '相声',
  kuaiBan:       '快板',
  roleMonologue: '角色自述',
  roleRecite:    '角色诵读',
  roleExperience:'经历台词',
  roleRelation:  '关系对话',
  roleInsult:    '角色辱骂',
  roleSexInsult: '性辱骂',
  roleExtract:   '角色提取',
  dianPingShangXi: '点评赏析',
  yiLunWen:     '锦绣议论',
  jiXuWen:      '锦绣记叙',
  youJiWen:     '锦绣游记',
  ciFuWen:      '锦绣辞赋',
  character:     '角色卡',
  world:         '创作辅助/世界观',
  aids:          '生图识图',
  shengTuCiDian: '生图词典',
  eroticLetters: '情色书信',
  eroticFairyTale:'情色童话',
  eroticChecklist:'情色清单',
  eroticRiddle:  '情色杂物/闲情小品/谜语',
  eroticProverb: '情色杂物/闲情小品/歇后语',
  eroticCouplet: '情色杂物/闲情小品/对联',
  eroticHaiku:   '情色俳句',
  eroticQuote:   '情色语录',
  eroticDiary:   '情色日记',
  eroticMemo:    '情色备忘录',
  eroticQuiz:    '情色问卷',
  docContract: '情色杂物/记录文书/性奴契约',
  docPlan: '情色杂物/记录文书/调教计划',
  docTrainLog: '情色杂物/记录文书/调教日志',
  docSlaveLog: '情色杂物/记录文书/性奴日志',
  docReverse: '情色杂物/记录文书/反差婊的自我养成',
  docFemboy: '情色杂物/记录文书/伪娘的自我养成',
  docReward: '情色杂物/记录文书/奖惩台账',
  docProfile: '情色杂物/记录文书/性癖档案',
  docCuckold: '情色杂物/记录文书/绿奴契约',
  docHotwife: '情色杂物/记录文书/淫妻契约',
  docPet: '情色杂物/记录文书/宠物契约',
  docToilet: '情色杂物/记录文书/厕奴契约',
  lifeFood:      '情色杂物/生活消费/吃喝',
  lifeWear:      '情色杂物/生活消费/穿戴',
  lifeHome:      '情色杂物/生活消费/居家',
  lifeKink:      '情色杂物/生活消费/情趣',
  lifePlay:      '情色杂物/生活消费/玩乐',
  interactiveNovel:'互动小说',
  trpg:          'AI跑团',
  chatSim:       '聊天模拟',
  harem:         '后宫',
  contractBdsm:  '调教契约',
  eroticCasino:  '淫欲赌场',
  eroticStream:  '色情直播',
  fetishQuiz:    '性癖问答',
  fetishBank:    '性癖问答',
  fetishPaper:   '性癖问答',
  fetishExam:    '性癖问答',
  examRoom:      '性癖考场',
  orgyParty:     '淫乱派对',
  popSong:       '流行歌曲',
  junGe:         '军旅战歌',
  erGeTongYao:   '儿歌童谣',
  guiChuShenQu:  '鬼畜神曲',
  yingShiZhuTiQu:'影视金曲',
  jiuZhuoGe:     '酒桌欢歌',
  songGeShengYong:'颂歌圣咏',
  xiHaShuoChang: '嘻哈说唱',
  historyAdapt:  '历史改编',
  mythAdapt:     '神话改编',
  classicAdapt:  '名著改编',
  fableAdapt:    '寓言改编',
  refDoc:        '创作辅助/文风分析',
  inspiration:   '创作辅助/灵感板',
  lifeDoc:       '情欲文学/生活纪实',
  newspaper:     '新闻媒体',
  letter:        '情欲工坊/书信社交/书信',
  note:          '情欲工坊/书信社交/便条',
  chatLog:       '情欲工坊/书信社交/聊天记录',
  socialPost:    '情欲工坊/书信社交/社交动态',
  shenghuoGuanshang: '生活观赏',
};

// 反向映射：中文目录名 -> 英文 key
var 存储键 = {};
(function() {
  for (var key in 存储目录) {
    存储键[存储目录[key]] = key;
  }
})();

window.存储目录 = 存储目录;
window.STORE_DIRS = 存储目录;
window.存储键 = 存储键;
window.STORE_KEYS = 存储键;
